apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myservice
    harness.io/color: blue    # 👈 required for Blue/Green

spec:
  type: ClusterIP
  selector:
    app: myservice
    harness.io/color: blue    # 👈 required for Blue/Green
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP